=== Marukovich/XmlXsdTask/data/devices.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        
        targetNamespace="http://www.pc.by/shop/devices"
        xmlns:tns="http://www.pc.by/shop/devices"
        elementFormDefault="qualified">
    
    <element name="devices">
        <complexType>
            <sequence>
                <element ref="tns:device" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="device" type="tns:Device" abstract="true"/>
    <element name="graphic-card" type="tns:Graphic-card" substitutionGroup="tns:device"/>
    <element name="central-processor" type="tns:Central-processor" substitutionGroup="tns:device"/>
    <element name="power-unit" type="tns:Power-unit" substitutionGroup="tns:device"/>
    <complexType name="Device">
        <sequence>
            <element name="name" type="string"/>
            <element name="origin" type="string"/>
            <element name="price" type="decimal"/>
            <element name="type" type="tns:Type"/>
            <element name="critical" type="string"/>
        </sequence>
        <attribute name="device-id" type="tns:device-id" use="required"/>
        <attribute name="title" type="string" use="required"/>
    </complexType>
    <complexType name="Graphic-card">
        <complexContent>
            <extension base="tns:Device"/>
        </complexContent>
    </complexType>
    <complexType name="Central-processor">
        <complexContent>
            <extension base="tns:Device"/>
        </complexContent>
    </complexType>
    <complexType name="Power-unit">
        <complexContent>
            <extension base="tns:Device"/>
        </complexContent>
    </complexType>
    <simpleType name="device-id">
        <restriction base="ID">
            <pattern value="\w{2}\d{2,5}"/>
        </restriction>
    </simpleType>
    <simpleType name="price">
        <restriction base="decimal">
            <minInclusive value="10"/>
            <maxInclusive value="2500"/>
        </restriction>
    </simpleType>
    <complexType name="Type">
        <sequence>
            <element name="is-periphery" type="string"/>
            <element name="energy-consumption" type="int"/>
            <element name="numbers-of-coolers" type="int"/>
            <element name="component-group" type="string"/>
            <element name="ports" type="string"/>
        </sequence>
    </complexType>
</schema>

=== Marukovich/XmlXsdTask/data/devices.xml
<?xml version="1.0" encoding="UTF-8" ?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.pc.by/shop/devices"
             xsi:schemaLocation="http://www.pc.by/shop/devices devices.xsd">
    <graphic-card device-id="gc100" title="graphic card">
        <name>RTX3070Ti</name>
        <origin>Taiwan</origin>
        <price>1999.99</price>
        <type>
            <is-periphery>yes</is-periphery>
            <energy-consumption>450</energy-consumption>
            <numbers-of-coolers>2</numbers-of-coolers>
            <component-group>periphery</component-group>
            <ports>displayport,hdmi</ports>
        </type>
        <critical>no</critical>
    </graphic-card>

    <central-processor device-id="cp005" title="central processor">
        <name>i7 11900K</name>
        <origin>USA</origin>
        <price>979.99</price>
        <type>
            <is-periphery>no</is-periphery>
            <energy-consumption>170</energy-consumption>
            <numbers-of-coolers>0</numbers-of-coolers>
            <component-group>main</component-group>
            <ports>none</ports>
        </type>
        <critical>yes</critical>
    </central-processor>
</devices>
